/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hdos_rsyygh_testjni_TestNdk */

#ifndef _Included_com_hdos_rsyygh_testjni_TestNdk
#define _Included_com_hdos_rsyygh_testjni_TestNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hdos_rsyygh_testjni_TestNdk
 * Method:    helloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hdos_rsyygh_testjni_TestNdk_helloWord
  (JNIEnv *, jclass);

/*
 * Class:     com_hdos_rsyygh_testjni_TestNdk
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hdos_rsyygh_testjni_TestNdk_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
